/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_onestravel_ndk_ffmpeg_render_VideoPlayer */

#ifndef _Included_cn_onestravel_ndk_ffmpeg_render_VideoPlayer
#define _Included_cn_onestravel_ndk_ffmpeg_render_VideoPlayer
#ifdef __cplusplus
extern "C" {
#include "libyuv.h"
#endif
/*
 * Class:     cn_onestravel_ndk_ffmpeg_render_VideoPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_cn_onestravel_ndk_ffmpeg_render_VideoPlayer_render
  (JNIEnv *, jclass , jstring, jobject);

/*
 * Class:     cn_onestravel_ndk_ffmpeg_render_VideoPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_cn_onestravel_ndk_ffmpeg_render_VideoPlayer_sound
        (JNIEnv *, jobject , jstring, jobject);

/*
 * Class:     cn_onestravel_ndk_ffmpeg_render_VideoPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_cn_onestravel_ndk_ffmpeg_render_VideoPlayer_play
        (JNIEnv *, jobject , jstring, jobject);



//JNIEXPORT void JNICALL
//Java_cn_onestravel_ndk_ffmpeg_render_VideoPlayer_destroy(JNIEnv* , jobject ,
//                                                         jstring , jobject);


#ifdef __cplusplus
}
#endif
#endif
