/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class _Included_cn_onestravel_ndk_ffmpeg_VideoUtils */

#ifndef _Included_cn_onestravel_ndk_ffmpeg_VideoUtils
#define _Included_cn_onestravel_ndk_ffmpeg_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     _Included_cn_onestravel_ndk_ffmpeg_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_onestravel_ndk_ffmpeg_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
